name: youtube_player
description: A responsive angular wrapper for playing Youtube videos
version: 0.0.1
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:  
  angular: ^5.2.0  
  fo_components: ^1.0.1+1