name: youtube_player
description: A responsive angular wrapper for playing Youtube videos
version: 0.0.15
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  angular: ^7.0.0
  fo_components:
    git:
      url: https://github.com/afpatmin/fo_components.git
      ref: null-safety
  sass_builder: ^2.1.4
